name: Build and Deploy

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16  

    - name: Build
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o main lambda/main.go
        zip deployment.zip main

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: deployment
        path: deployment.zip

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2
    
    - name: Terraform Init
      run: terraform -chdir=s3 init

    - name: Terraform Plan
      run: terraform -chdir=s3 plan

    - name: Terraform Apply
      run: terraform -chdir=s3 apply -auto-approve
