name: sqs

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.6.6  

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - name: Initialize Terraform
      run: terraform -chdir=sqs init

    - name: Validate Terraform
      run: terraform -chdir=sqs validate

    - name: Plan Terraform
      run: terraform -chdir=sqs plan -out=tfplan

    - name: Apply Terraform
      run: terraform -chdir=sqs apply -auto-approve tfplan
